spring.application.name=docifestas

# Conexão com o banco (O nome que você disse que era: software)
spring.datasource.url=jdbc:mysql://localhost:3306/software?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=degespr23
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true